### ISSUE TITLE
Remove `pytest` dependency from docker image

### ISSUE THREAD

**Issue by lukasz-mitka** [FiniteStateInc/binary-scan#11]
Please speed up build and reduce image size by changing it so `pytest` and it's dependencies don't end up in docker image build by this action.
One of the solution would be to moving `pytest` to `requirements-dev.txt` file.

Also please look into `.dockerignore` to skip files that are not used in the final image.

**Comment by phillipcurl** [comment]
Hi @lukasz-mitka! Thank you for this feedback. This is a great suggestion, and we'll include these changes in a release this week. I'll follow up with you here once that release has shipped. Thank you!

**Comment by cpfarherFinitestate** [comment]
Hi, [release 2.0.1](https://github.com/FiniteStateInc/binary-scan/tree/v2.0.1) manage the pytest as @lukasz-mitka mentioned. Probably we could close this issue safely @phillipcurl .
